[jaekim] ADD : day4까지 과제 올림
keinn51/React-Study pull request #4
Opened 2022-07-11 09:39 UTC by jae-hwan-kim

요청합니다. jaekim 폴더 추가했습니다.

2022-07-11 11:52 UTC, keinn51 requested changes
`.gitignore` 을 만들어서 `node_modules` 는 안 올라오도록 해주실 수 있나요? 해당 파일의 크기가 너무 커서 원래 깃을 올릴 때에는 `package.json` 만 올리고는 한답니다!

2022-07-11 23:05 UTC, jae-hwan-kim commented
ignore 파일 추가했습니다!

2022-07-11 23:12 UTC, jae-hwan-kim commented
4f7c169 커밋에 노드 모듈 빼고 커밋했는데, 잘된게 맞을까요..?!

2022-07-12 02:19 UTC, keinn51 approved these changes
굿굿 좋은 코드 잘 봤습니다! 저도 배워가는게 있는 것이 보이니까, 재킴님이 이제 리액트를 많이 아셨다는 생각이 드는군요! 직접 머지해보세요~!

2022-07-12 02:19 UTC, keinn51 commented on jaekim/practice/together/src/login/login_style.css
> +  transform: translate(-50%, -50%);
이런 CSS는 다 직접 찾아서 하신 건가용??

2022-07-12 02:19 UTC, keinn51 commented on jaekim/practice/together/src/event/intro.js
> +          <button className="create_button" onClick={() =>props.setPage(props.page ? false : true)}>
삼항 연산자 굿굿

2022-07-12 02:19 UTC, keinn51 commented on jaekim/practice/together/src/event/footer.js
> +      return <img key={image} src={require(`../profile ${image}.png`)} className="profile" alt=""/>
헐 이런 방식이 있었군요? 어떻게 어디서 알아오신거지; 저는 이태껏 하나하나 import하고 있었는데 고쳐야겠는걸요?

2022-07-12 02:19 UTC, keinn51 commented on jaekim/practice/together/src/event/event_style.css
> +  font-size: larger;
![image](https://user-images.githubusercontent.com/79993356/178394136-9f7857a4-1864-4ea2-a0c8-baacf09bf964.png)

larger 도 처음 봅니다 신기신기!

2022-07-12 02:49 UTC, jae-hwan-kim commented on jaekim/practice/together/src/login/login_style.css
> +  transform: translate(-50%, -50%);
네네! absolute 했을 때, 가운데로 보내는 방법 찾아봤습니당ㅋㅋ

2022-07-12 02:49 UTC, jae-hwan-kim commented on jaekim/practice/together/src/event/intro.js
> +          <button className="create_button" onClick={() =>props.setPage(props.page ? false : true)}>
경슬님한테 많이 배웠습니당 하하

2022-07-12 02:57 UTC, jae-hwan-kim commented on jaekim/practice/together/src/event/footer.js
> +      return <img key={image} src={require(`../profile ${image}.png`)} className="profile" alt=""/>
"how to render image using map in react" 이 키워드로 검색해서 스택오버플로우에서 찾았습니다ㅎㅎ
https://stackoverflow.com/questions/45713362/how-to-render-images-with-react-js-using-map-or-loop

근데 이렇게 하면 디렉토리 위치를 적게 되더라구요

2022-07-12 02:57 UTC, jae-hwan-kim commented on jaekim/practice/together/src/event/event_style.css
> +  font-size: larger;
풀리퀘가 이런 재미가 있군여...! 코드 줄 별로 코멘트가 가능하네요ㅋㅋ

2022-07-12 02:58 UTC, jae-hwan-kim commented
머지하겠습니다~!

2022-07-12 02:58 UTC, merged

2022-07-12 04:28 UTC, keinn51 commented on jaekim/practice/together/src/login/login_style.css
> +  transform: translate(-50%, -50%);
와우 대단하네요 수고하셨습니다!

2022-07-12 04:29 UTC, keinn51 commented on jaekim/practice/together/src/event/footer.js
> +      return <img key={image} src={require(`../profile ${image}.png`)} className="profile" alt=""/>
키워드 검색을 잘 하시는군요..! 저렇게 찾는 것도 개발자의 능력 아니겠습니까 훟ㅎ

2022-07-12 04:29 UTC, keinn51 commented on jaekim/practice/together/src/event/event_style.css
> +  font-size: larger;
그래서 풀리퀘를 해달라고 한 것입니다 코드 보기!